### ISSUE TITLE
Blocks creating space for no reason

### ISSUE THREAD

**Issue by Nesquickforce** [khoi-nguyen/teaching#20]
Please change 
::: Solution
$$6a^9 \times 7x^9 = 6 \times {\color{orange} a^9 \times 7} \times a^9 = 6 \times {\color{orange} 7 \times a^9} \times a^9 = 42x^{18}$$
:::
such that no space is created between the environment and the working.

**Comment by khoi-nguyen** [comment]
LaTeX issue happening for long equations in double dollars. Maybe une single dollars for them.
